### ISSUE TITLE
can't connect to db in `./backend` folder

### ISSUE THREAD

**Issue by ralyodio** [semanser/codel#1]
```
$ go run .

2024/03/23 05:22:11 /home/ettinger/src/apps/codel/backend/main.go:31
[error] failed to initialize database, got error failed to connect to `host=localhost user=postgres database=ai-coder`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)
2024/03/23 05:22:11 failed to connect database: failed to connect to `host=localhost user=postgres database=ai-coder`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)
exit status 1
```

**Comment by semanser** [comment]
Thanks for the report! Some of the env variables were missing in the readme (as well as hardcoded in the code 😅)

I updated the code and the readme:
https://github.com/semanser/codel?tab=readme-ov-file#environment-variables

Make sure that you fetch the latest version with `git pull` before trying again ;)

**Comment by ralyodio** [comment]
Can you supoirt a global .env file in the root?

**Comment by semanser** [comment]
It's using https://pkg.go.dev/os#Getenv to get the env variables so you should be able to use something like `direnv` if you want a per-project env file.

https://direnv.net/

**Comment by ralyodio** [comment]
sigh. why can't people just follow standards.

**Comment by ralyodio** [comment]
still doesn't work:

#!/bin/bash

export OPEN_AI_KEY=sk-ddd
export DATABASE_URL=postgres://test:test@localhost:5432/test
export DOCKER_HOST=/var/run/docker.sock

**Comment by ralyodio** [comment]
`2024/03/23 06:19:42 failed to initialize Docker client: unable to parse docker host `/var/run/docker.sock``

**Comment by semanser** [comment]
It seems to be the exact issue as described here: https://stackoverflow.com/a/74148162

What worked for me is `unix:///Users/semanser/Library/Containers/com.docker.docker/Data/docker.raw.sock`. I'm on Intel/MacOS so in your case it can be different.

**Comment by ralyodio** [comment]
needed `unix://`
